### ISSUE TITLE
Use it on none joomla Site

### ISSUE THREAD

**Issue by jacabang** [getbible/Joomla-3-Component#10]
Good Day,

I was wondering if I can use this API for a non joomla website or it only support joomla.

Sorry for the inconvenience,
Thank you and God bless.

**Comment by Llewellynvdm** [comment]
Hi,

You can use this API on none Joomla websites, you will then basically use getbible.net's API instead of your own API on your own Joomla website.

You see this component is an API that gets added to any Joomla website that use it. It not only makes API calls it is an API.

So to use it on other websites you can with Javascript/jQuery make API calls to the getbible.net's API that will return JSON object with scripture like the following:

whole version (only one at a time)
[https://getbible.net/json?v=kjv](https://getbible.net/json?v=kjv)

whole book (only one at a time)
[https://getbible.net/json?p=Psalms](https://getbible.net/json?p=Psalms)

whole chapter (only one at a time)
[https://getbible.net/json?p=Psalms 119](https://getbible.net/json?p=Psalms 119)

or multiple verses (up to seven)
[https://getbible.net/json?p=Psalms 119:1;James 3:1-4;John 1:1-51;John 2:1-25; Gen 1:5](https://getbible.net/json?p=Psalms 119:1;James 3:1-4;John 1:1-51;John 2:1-25; Gen 1:5)

or just one verse.
[https://getbible.net/json?p=Psalms 119:1](https://getbible.net/json?p=Psalms 119:1)

To change the version/translation that gets returned since KJV is the default you should simply add the v tag to the call, like this:
[https://getbible.net/json?p=Psalms 119:1;James 3:1-4;John 1:1-51;John 2:1-25; Gen 1:5&v=aov](https://getbible.net/json?p=Psalms 119:1;James 3:1-4;John 1:1-51;John 2:1-25; Gen 1:5&v=aov)

Here is a page that will give you some jQuery example of how to make an ajax call, and at the bottom of the page is the list of available versions.

Hope this helps, let me know.
