### ISSUE TITLE
Malware detected

### ISSUE THREAD

**Issue by realsoonlee** [getbible/Joomla-3-Component#22]
Hi,

Instead of using jQuery to access the json data, I am trying to do so using C# HttpClient. However, I keep getting "Forbidden access. Malware detected." 

With the same code, I am able to get the data from BibleGateway.

Did I miss something?

Thanks
Soon Lee

**Comment by Llewellynvdm** [comment]
This may be due to the `jsonp` return set that is used for jQuery, add `&raw=true` to your query and see if the issue gets resolved.

**Comment by realsoonlee** [comment]
Thanks Llewellynvdm. 

Didn't expect you to answer so quickly. :)
Unfortunately, that additional parameter doesn't help. :(

**Comment by Llewellynvdm** [comment]
That is as much as I can help you, the result set in json and with the raw parameter it removes the jsonp function call (which is considered bad practice now a days). Well I am online at the moment so could respond.

I am working on a update to the API since I did build it like 4 years ago (and have not really made any changes to it since). Hoping to address all these kind of issues. So could you give me some form of speck to how the C# HttpClient would expect the result set headers and handshake to look. I don't like and therefore have not worked with C# but I have no trouble to at-least insure that the API works across language cultures.

**Comment by realsoonlee** [comment]
I appreciate your work on this API so as to bless others.

Since I am still new to ajax calls from C# code-behind, I really do not know what to tell you. I have worked on using jQuery Ajax calls to C# Web service but not the other around.

Anyway, thank you so much for your time.

Have a great day!

**Comment by Llewellynvdm** [comment]
Okay in that case, I will close this issue, and once you have some answer please do not hesitate to get back to me!
