### ISSUE TITLE
JSON url format

### ISSUE THREAD

**Issue by foxxr80** [getbible/Joomla-3-Component#8]
What is the proper url syntax for getting multiple chapters of a book? For example, Judges 17-21. I know I can do this:

https://getbible.net/json?p=Judges17:1-13;18:1-31;19:1-30;20:1-48;21:1-25

but this doesn't work:

https://getbible.net/json?p=Judges17-21

Also, can I get more than 7 chapters returned at a time? If I did something like:

https://getbible.net/json?p=Jeremiah1:1-19;2:1-37;3:1-25;4:1-31;5:1-31;6:1-30;7:1-34;8:1-22;9:1-26;10:1-25;11:1-23;12:1-17;13:1-27;14:1-22;15:1-21;16:1-21

It will only give me chapter 1 -7, and then I would have to edit the url and make a second call to get chapters 8 -14, and then a third call to get 15-16. Perhaps my syntax is just wrong and is causing this issue. Thanks!

**Comment by Llewellynvdm** [comment]
Sorry but at this time getBible does not allow for multiple chapters to be fetched with one query, you can get:

whole version (only one at a time)
`https://getbible.net/json?v=kjv`

whole book (only one at a time)
`https://getbible.net/json?p=Psalms`

whole chapter (only one at a time)
`https://getbible.net/json?p=Psalms 119`

or multiple verses (up to seven)
`https://getbible.net/json?p=Psalms 119:1;James 3:1-4;John 1:1-51;John 2:1-25; Gen 1:5`

or just one verse.
`https://getbible.net/json?p=Psalms 119:1`

So you can make multiple calls getting one chapter after the other or just get the whole book and use only the chapters you need. I mean it is a json object :)

Then about the multiple verses it will only [return 7](https://github.com/getbible/Joomla-3-Component/blob/master/admin/models/get.php#L705) "verses" or lets say 7 query sections that call a set of verses separated with a semicolon, at a time. Do note that if any one of those queries/sections call a whole chapter it will only return that chapter.

So that means:
`https://getbible.net/json?p=Psalms 119:1;James 3:1-4;John 1;John 2:1-25; Gen 1:5`
Will only return John1 and none of the other verses, but:
`https://getbible.net/json?p=Psalms 119:1;James 3:1-4;John 1:1-51;John 2:1-25; Gen 1:5`
Will return five sets of verses.

Hope this helps, let me know.

**Comment by foxxr80** [comment]
Yes, this does help a lot. Thanks!
